
name: Continuous integration
on: push

jobs:
  deploy:
    name: Build and deploy to GitHub Pages
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.3

      - name: Fetch list of proposals
        run: |
          ./build.sh
          # Deploy all the files we need in the generated site to the `dist/` folder.
          mkdir -p dist/
          cp -r css/ thirdparty/ proposals/ .nojekyll index.html favicon.png dist/
          ls -la dist/*

      - name: Deploy to GitHub Pages 🚀
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # The branch the action should deploy to.
          BRANCH: gh-pages
          # The folder the action should deploy.
          FOLDER: dist
          # Artifacts are large, don't keep the branch's history
          SINGLE_COMMIT: true
