
name: Continuous integration
on:
  push:
  schedule:
    # Every day at midnight (UTC).
    # This keeps the list of proposals fresh.
    - cron: '0 0 * * *'

jobs:
  deploy:
    name: Build and deploy to GitHub Pages
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Fetch list of proposals
        run: |
          pip install -r requirements.txt
          ./build.py
          # Deploy all the files we need in the generated site to the `dist/` folder.
          mkdir -p dist/
          cp -r css/ thirdparty/ proposals.json .nojekyll index.html favicon.png dist/
          ls -la dist/*

      - name: Minify files
        run: |
          curl -fsSLO https://github.com/tdewolff/minify/releases/download/v2.9.15/minify_linux_amd64.tar.gz
          tar xf minify_linux_amd64.tar.gz minify
          ./minify --recursive dist --output .

      - name: Deploy to GitHub Pages 🚀
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # The branch the action should deploy to.
          BRANCH: gh-pages
          # The folder the action should deploy.
          FOLDER: dist
          # Artifacts are large, don't keep the branch's history
          SINGLE_COMMIT: true
